sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.organization=${SONAR_ORG}

sonar.sources=src
sonar.tests=tests

sonar.cs.opencover.reportsPaths=**/coverage.cobertura.xml
sonar.coverage.exclusions=**/*Tests.cs